### ISSUE TITLE
追加アイデア

### ISSUE THREAD

**Issue by sakusaku3939** [nkzwlab/jnok-bingo#4]
- 問題： 盛り上がりが足りなそう
  - urataさんより
  - ドラムロールを追加する

- 問題： 80人もいる場合、一瞬でビンゴが終わりそう
  - 2列・行のビンゴでクリアにする
  - 逆ビンゴ
  - 参考： ビンゴになる確率
    - https://techracho.bpsinc.jp/nozue/2016_12_13/30804
  - 参考：ビンゴにかかる時間の計算サイト
    - https://bingo-time-simulator.vercel.app/
    - 景品3つ、1番号あたり10秒の場合、約5~7分で終わる

**Comment by sakusaku3939** [comment]
@s19514tt こちら何か意見があればお願いします！ :pray:

**Comment by s19514tt** [comment]
ドラムロールはめっちゃいいと思う
逆ビンゴはありだと思うけど、少し実装変えないといけなさそうだね〜
せっかくなら普通のビンゴもやりたいし、1回目は普通にやって2回目景品渡す時に逆にする？
最後の1人だけ一番豪華な景品をあげるとかでもいいきが

2列は見た目的にもわかりにくいし、個人的には好きじゃないかも

**Comment by s19514tt** [comment]
せっかくならドラムロールの実装とか誰かにお願いしたけど適任の人いるかな？

**Comment by sakusaku3939** [comment]
普通のビンゴと同時に逆ビンゴ開催するのアリかもです
例えば、1位、2位、最下位(逆ビンゴ賞)に景品を渡す感じでどうですか？（すぐ揃って終わることは無さそうです）

**Comment by sakusaku3939** [comment]
他に担当する人いなさそうなので自分がドラムロール追加しておきますー
